import React from 'react';
import Head from "next/head";
import {GetStaticPaths, GetStaticProps} from "next";
import client from "../../Contentful";
import {IArticleFields, IArticle} from "../../contentful";
import {documentToReactComponents} from "@contentful/rich-text-react-renderer";

export default function Article({article}: {article: IArticle}) {
    return (
        <>
            <Head>
                <title>{article.fields.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1 className='text-3xl font-bold my-20 mx-10'>{article.fields.title}</h1>
                <div className='m-10'>
                    {documentToReactComponents(article.fields.content!)}
                </div>
            </main>
        </>
    )
}

export const getStaticPaths: GetStaticPaths = async () => {
    const articleEntries = await  client.getEntries<IArticleFields>({
        content_type: 'article',
        select: 'fields.slug'
    })

    return {
        paths: articleEntries.items.map(item =>  {
            return {
                params: {
                    article: item.fields.slug
                }
            }
        }),
        fallback: false
    }
}

export const getStaticProps: GetStaticProps = async ({params}) => {
  const slug = params!.article;

  const articleEntries = await  client.getEntries<IArticleFields>({
      content_type: 'article',
      limit: 1,
      'fields.slug': slug
  })

    const [article] = articleEntries.items;
    return {
        props: {
           article
        },
    }
}
