import type {GetStaticProps} from 'next'
import Head from 'next/head'
import client from "../Contentful/index";
import {IArticle, IArticleFields, IHome, IHomeFields} from "../contentful";
import { documentToReactComponents } from '@contentful/rich-text-react-renderer';
import Link from "next/link";


export default function Home({home, articles}: {home: IHome, articles: IArticle[]}) {
  return (
    <div>
      <Head>
        <title>{home.fields.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <div className='text-center p-5 text-white'
              style={{
                  background: `url('${home.fields.background?.fields.file.url}') no-repeat center/cover`,
                  minHeight: 300}}>
              <h1 className="text-3xl font-bold mt-20">{home.fields.title}</h1>
              <div className='mb-5'>
                  {documentToReactComponents(home.fields.description!)}
              </div>
          </div>
          <section className='flex justify-center wrap'>
              {articles.map( article => {
                  return (
                      <div key={article.fields.slug} className='w-80 mx-auto my-4 border p-3'>
                          <p className="text-xl font-bold mb-3">{article.fields.title}</p>
                          <p>{article.fields.description}</p>
                          <Link href={`/articles/${article.fields.slug}`}>
                              <button className='bg-gray-700 bottom-0 rounded-xl mt-3 p-2 w-full text-white'>{article.fields.action}</button>
                          </Link>
                      </div>
                  )
              })}
          </section>
      </main>

    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
    const home = await client.getEntries<IHomeFields>({
        content_type: 'home',
        limit: 1
    });

    const [homePage] = home.items;
    const articleEntries = await client.getEntries<IArticleFields>({
        content_type: 'article',
        select: 'fields.title,fields.slug,fields.description,fields.action'
    });

    return {
        props: {
            title: 'Мой блог',
            home: homePage,
            articles: articleEntries.items
        },
        revalidate: 3600
    }
}
